[build]
builder = "nixpacks"
buildCommand = "python -m pip install --upgrade pip && cd FlaskBackend && pip install -r requirements.txt"

[deploy]
startCommand = "cd FlaskBackend && gunicorn --worker-class eventlet -w 1 'Formatting.app:app'"
healthcheckPath = "/api/health"
restartPolicyType = "on_failure"

[nixpacks]
python_version = "3.11"
